version: '3'
services:
  server:
    container_name: 'server'
    build:
      context: .
      dockerfile: Dockerfile_ec2
    tty: true
    volumes:
      - ../aws/credentials:/.aws/credentials
      - ./:/app
    working_dir: /app
    env_file:
      - ./env.example
    networks:
      - server
  db:
    container_name: 'db'
    build:
      context: .
      dockerfile: Dockerfile_mariadb
    restart: always
    command: mysqld
    ports:
      - 3306:3306
    volumes:
        - database:/var/lib/mysql
    env_file:
      - ./env.example
    networks:
      - server

networks:
  server:
    driver: bridge
volumes:
    database:
