FROM amazonlinux:2

#RUN yum update
#RUN yum install unzip git mysql hostname lsof -y

#RUN python -m ensurepip --default-pip
#RUN pip install --upgrade pip
#RUN pip install  wheel pandas pandas-datareader PyMySQL Flask pathlib

EXPOSE 5000